# Generated by Django 4.0 on 2021-12-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allquestion',
            name='question_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_numner',
            field=models.IntegerField(),
        ),
    ]
