# Generated by Django 4.0 on 2021-12-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptestapp', '0004_correctqa_resultqa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='anwsers',
            new_name='answers',
        ),
    ]
