# Generated by Django 4.0 on 2021-12-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptestapp', '0005_rename_anwsers_questionanswer_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='introvertqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('answer_number', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='correctqa',
            new_name='extrovertqa',
        ),
    ]
